---
- name: This playbook sets up NZ R Shiny infrastructure with Vagrant
  hosts: vagrant
  become: true
  become_user: root

  vars_files:
    - vars/default.yml

  roles:
    - locale
    - base
    #- postgresql
    - nginx
    - r
    - shiny
    - rapps

- name: This playbook sets up NZ R Shiny infrastructure
  hosts: catalyst
  become: true
  become_user: root

  # pre_tasks:
  #   - raw: sudo apt-get -y install python

  vars_files:
    - vars/default.yml

  vars:
    letsencrypt_enabled: true

  roles:
    - locale
    - base
    - security
    - nginx
    - r
    - shiny
    - rapps
